pytest:
  image: python:3.10-alpine
  script:
    - sh tests/start_tests_gitlab.sh
    # - sed -i "s#<source>/builds/DasMoorhuhn/autopicture-v3/src</source>#<source>${CI_PROJECT_DIR}</source>#g" coverage.xml
  coverage: '/Code coverage: \d+(?:\.\d+)?/'
  artifacts:
    name: "$CI_JOB_NAME"
    reports:
      junit: report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
